### ISSUE TITLE
Since updating to v0.6.x can't open apps on TV anymore

### ISSUE THREAD

**Issue by Mazori01** [ollo69/ha-samsungtv-smart#151]
When trying to open an app with the **Media Player: Play media** using **Netlfix** as **content id** and **app** as **content type** I get the response "_Message malformed: Integration '' not found_"

When I try to open an app with an Script I get this response "_Failed to call service script/start_netflix. 'NoneType' object has no attribute 'get'_"

But when using the service to press keys from the remote it works.
Can somebody help?

**Comment by ollo69** [comment]
Please attach log file with error and diagnostic file

**Comment by Mazori01** [comment]
[Log file.txt](https://github.com/ollo69/ha-samsungtv-smart/files/8374001/Log.file.txt)
[config_entry-samsungtv_smart-58ac55551713f74ea50ab0a924d4f8eb.json.txt](https://github.com/ollo69/ha-samsungtv-smart/files/8374002/config_entry-samsungtv_smart-58ac55551713f74ea50ab0a924d4f8eb.json.txt)

**Comment by antonio1475** [comment]
Same here. I was able before as mentioned in [issue 109 ](https://github.com/ollo69/ha-samsungtv-smart/issues/109#issuecomment-1072779888)

With this
```
service: media_player.play_media
data:
  media_content_id: 3201907018807
  media_content_type: app
target:
  entity_id: media_player.samsungtv_smart
```

I get:

```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/samsungtv_smart/media_player.py:1378
Integration: SamsungTV Smart (documentation, issues)
First occurred: 21:21:02 (1 occurrences)
Last logged: 21:21:02

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1456, in async_play_media
    await self._async_launch_app(media_id)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1378, in _async_launch_app
    if app_id_from_list := self._app_list.get(app_id):
AttributeError: 'NoneType' object has no attribute 'get'
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/samsungtv_smart/media_player.py:1378
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:21:02 (1 occurrences)
Last logged: 21:21:02

[140703446305808] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 630, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1456, in async_play_media
    await self._async_launch_app(media_id)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1378, in _async_launch_app
    if app_id_from_list := self._app_list.get(app_id):
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by antonio1475** [comment]
But doing it with the app name (or id?) in 0.5.0 works fine with no errors! :smiley: 
```
service: media_player.play_media
data:
  media_content_id: kIciSQlYEM.plex  (or 9Ur5IzDKqV.TizenYouTube)
  media_content_type: app
target:
  entity_id: media_player.samsungtv_smart
```

I upgraded back to 0.6.2 and errors + the app won't open.
Sorry for the triple-posting!

**Comment by ollo69** [comment]
Really busy on this days. I will take a look asap....

**Comment by ollo69** [comment]
I identified and fixed the issue. It will be available with next release within next week.

**Comment by antonio1475** [comment]
Can confirm it works again with the update and this issue can probably be closed (although I'm not OP). Thank you!!
